# Generated by Django 5.1.6 on 2025-03-13 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MOVIES', '0003_movie_dislike_movie_users_movie_like_movie_users_and_more'),
        ('QUIZZES', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie_quiz', to='MOVIES.movie'),
        ),
    ]
