# Generated by Django 5.1.6 on 2025-03-13 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QUIZZES', '0002_quiz_quiz_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='quiz_movie',
        ),
    ]
