# Generated by Django 5.1.6 on 2025-03-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACCOUNTS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.TextField(default='nickname', max_length=20),
        ),
    ]
