# Generated by Django 5.1.6 on 2026-03-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ACCOUNTS", "0002_user_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(default="nickname", max_length=20),
        ),
        migrations.AlterField(
            model_name="user",
            name="region",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
