# Generated by Django 5.1.6 on 2025-02-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MOVIES', '0002_cast_delete_trend'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='normalized_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
