# Generated by Django 5.1.6 on 2026-01-30 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MOVIES", "0003_movie_dislike_movie_users_movie_like_movie_users_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="is_complete",
            field=models.BooleanField(default=False),
        ),
    ]
