# Generated by Django 5.1.6 on 2026-01-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MOVIES", "0004_movie_is_complete"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="last_detail_fetched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
