# Generated by Django 5.1.6 on 2026-02-03 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MOVIES", "0005_movie_last_detail_fetched_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="release_date_kr",
            field=models.DateField(blank=True, null=True),
        ),
    ]
